# Generated by Django 5.2 on 2025-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_alter_orden_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
