# Generated by Django 5.2 on 2025-05-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_orden_ciudad_entrega_orden_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='ciudad_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='telefono_contacto',
        ),
    ]
