# Generated by Django 5.2 on 2025-05-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_prod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
