# Generated by Django 5.2 on 2025-05-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_categoria_prod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='ProductoJewe',
        ),
        migrations.AlterModelOptions(
            name='productojewe',
            options={'verbose_name': 'productojewe', 'verbose_name_plural': 'productosjewe'},
        ),
    ]
